### ISSUE TITLE
[BUG] `ZarrConverter` fails for 3D+2D MM datasets

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#327]
Related to https://github.com/czbiohub/iohub/issues/82

The `ZarrConverter` cannot handle 3D+2D MM datasets (datasets where one or more of the MDA channels has the "acquire z-stack" box unchecked). 

I'm posting this here instead of `iohub` because we're about to deprecate `recOrder`'s`ZarrConverter`, but I need to use the `ZarrConverter` for a 3D+2D MM dataset before the `iohub` converter will be ready. 

This can close when:
- an `iohub` 3D+2D MM converter becomes available or 
- a fix to this `ZarrConverter` is merged into `recOrder`.

**Comment by talonchandler** [comment]
@ziw-liu should this issue be transferred to `iohub`?

**Comment by talonchandler** [comment]
Thanks for fixing iohub #82, @ziw-liu, but this issue is separate. 

If I run `iohub convert -i /hpc/projects/compmicro/rawdata/other/NIC\ QLIPP/2022_12_01\ PtK\ cells/FOV1_1/ -o ~/test.zarr` (or the nearly equivalent `recorder convert` call) I receive
```
iohub: N-dimensional bioimaging I/O 

Status: |▎               |5/246 (Time Remaining: 00:05), 45.22it/s]
Traceback (most recent call last):
  File "/home/talon.chandler/.conda/envs/recorder-test/bin/iohub", line 8, in <module>
    sys.exit(cli())
  File "/home/talon.chandler/.conda/envs/recorder-test/lib/python3.9/site-packages/click/core.py", 
line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/talon.chandler/.conda/envs/recorder-test/lib/python3.9/site-packages/click/core.py", 
line 1055, in main
    rv = self.invoke(ctx)
  File "/home/talon.chandler/.conda/envs/recorder-test/lib/python3.9/site-packages/click/core.py", 
line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/talon.chandler/.conda/envs/recorder-test/lib/python3.9/site-packages/click/core.py", 
line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/talon.chandler/.conda/envs/recorder-test/lib/python3.9/site-packages/click/core.py", 
line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/talon.chandler/iohub/iohub/cli/cli.py", line 84, in convert
    converter.run()
  File "/home/talon.chandler/iohub/iohub/convert.py", line 338, in run
    img_raw = self._get_image_array(*coord_reorder)
  File "/home/talon.chandler/iohub/iohub/convert.py", line 271, in _get_image_array
    return np.asarray(self.reader.get_image(p, t, c, z))
  File "/home/talon.chandler/iohub/iohub/multipagetiff.py", line 348, in get_image
    coord = self.coord_map[coord_key]  # (file, page, offset)
KeyError: (0, 0, 5, 0)
```
I'll suggest we reopen this issue, and transfer to `iohub`. What do you think?

It's not a high priority since I have a workaround that skips the fluorescence channels in #328.

**Comment by ziw-liu** [comment]
@talonchandler I just pushed https://github.com/czbiohub/iohub/pull/97/commits/2c0fdc72538fb9afe1f5ded670d6aa994f649b8d. The dataset will convert now.

**Comment by talonchandler** [comment]
Fantastic! All fixed now, @ziw-liu. This is going to save me a ton of headache on my next round of spindle analyses.
