### ISSUE TITLE
[BUG] Connection via pycromanager failing

### ISSUE THREAD

**Issue by dbcortes2042000** [mehta-lab/recOrder#480]
Running on Windows 11 with Anaconda, had to install with modified napari:
`pip install recOrder-napari[acq]==0.4.2rc1`

recOrder opens just fine now but does not connect to MicroManager which I have running an old Olympus IX81 body along with a TSI Thorlabs CS135MUN camera.

Already checked that I have enabled port 4827 for pycromanager.

I tried changing the order in which I open micromanager and napari w/ recOrder and consistently get the same error:

`Exception ignored in: <function _JavaObjectShadow.__del__ at 0x000001AB444B7BE0>
Traceback (most recent call last):
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 639, in __del__
    self._close()
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 563, in _close
    self._send(message)
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 577, in _send
    return self._get_bridge()._send(message)
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 325, in _send
    return self._main_socket.send(message, timeout=timeout)
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 116, in send
    raise Exception("Tried to send message through socket {}, which is already closed".format(self._port))
Exception: Tried to send message through socket 4827, which is already closed
Exception ignored in: <function _JavaObjectShadow.__del__ at 0x000001AB444B7BE0>
Traceback (most recent call last):
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 639, in __del__
    self._close()
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 563, in _close
    self._send(message)
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 577, in _send
    return self._get_bridge()._send(message)
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 325, in _send
    return self._main_socket.send(message, timeout=timeout)
  File "C:\Users\cortesadmin\anaconda3\envs\recOrder\lib\site-packages\pycromanager\zmq_bridge\_bridge.py", line 116, in send
    raise Exception("Tried to send message through socket {}, which is already closed".format(self._port))
Exception: Tried to send message through socket 4827, which is already closed`

**Comment by dbcortes2042000** [comment]
Went ahead and did a fresh reinstall of everything just in case. Still getting the same issue. recOrder gui does seem to connect at least partially to MM as it correctly imports the Config Group name from MM for the Meadowlark controller.

**Comment by talonchandler** [comment]
> recOrder gui does seem to connect at least partially to MM as it correctly imports the Config Group name from MM for the Meadowlark controller.

That's a good sign!

Our most recent successful tests have been with MicroManger nightly build 2023-04-26. Are you using this version? Are you using `pycromanager==0.27.2`?

Are there any other potential incompatibilities in [this table](https://github.com/mehta-lab/recOrder/blob/main/docs/microscope-installation-guide.md#compatibility-summary)?

**Comment by dbcortes2042000** [comment]
Only potential incompatibility I see is Windows 11 rather than 10. I am using the Micromanager nightly build recommended, Only thing I'm unsure of is the version of pycromanager. Is there an easy way to tell? I tried
`pycromanager --version`
on the console but that doesn't work.

**Comment by talonchandler** [comment]
You can find the pycromanager version with `pip list | grep pycromanager`. 

[This issue](https://github.com/micro-manager/pycro-manager/issues/635) seems related. Are you by chance running in debug mode from an IDE?

**Comment by dbcortes2042000** [comment]
> You can find the pycromanager version with `pip list | grep pycromanager`.
> 
> [This issue](https://github.com/micro-manager/pycro-manager/issues/635) seems related. Are you by chance running in debug mode from an IDE?

Haha for some reason 'grep' is not recognized on my Anaconda install... I looked in the micromanager folder and found a file called "PycroManagerJava-0.38.10.jar" if this is the version of pycromanager then I don't have the right one, but when I try to install 0.27.2 by using pip
`pip install pycromanager==0.27.2`

Terminal tells me that the requirements are already met and it changes PyQT to the incompatible form again...

I'm running Anaconda and using the Anaconda Powershell Prompt with administrator privileges. I don't think I have debug mode enabled on anything unless Anaconda enables it by default. I'd be happy to hop on a zoom call and go through the process with a clean install if you guys have the time to help me figure out where I'm going wrong!

**Comment by talonchandler** [comment]
@dbcortes2042000 can you share the following:

- your terminal output fom a failed run. Is there anything before what you wrote at the start of this thread?
- the output of `pip list` in the environment that is failing
- anything that is printed in the Calibration > Advanced text box while in recOrder's debug mode (open the Calibration > Advanced tab, use the dropdown to select debug mode, then try connecting to MicroManager.

**Comment by talonchandler** [comment]
Thanks @dbcortes2042000, this is helpful. I think [this narrows the failure to this section](https://github.com/mehta-lab/recOrder/blob/6c70732f812da763af6edb02e03d4c02c5d70627/recOrder/plugin/main_widget.py#L921C9-L935C53). 

I see two possible failure modes:

1. In MicroManager's device property browser, does the LC control box appear as `MeadowlarkLcOpenSource` or `MeadowlarkLC`. If `MeadowlarkLcOpenSource`, can you try removing and re-adding  the device to your config. I expect `MeadowlarkLC` when you use the latest device drivers. 

2. Did you name your MicroManager group `Channel` and set up `State*` presets similar to [this documentation](https://github.com/mehta-lab/recOrder/blob/main/docs/microscope-installation-guide.md#option-1-recommended-voltage-mode-calibration-installation). 

If (temporarily) renaming your MicroManager "Channel" fixes the issue, then this is a bug. `self.mmc.getConfigData("Channel", "State0")` should be `self.mmc.getConfigData(self.config_group, "State0")`

**Comment by dbcortes2042000** [comment]
@talonchandler it appears my issue was with the naming of the Meadowlark group. I did not realize it needed to be named "Channel" specifically! Changing the name has allowed recOrder to connect succesfully. Hopefully I won't have any more issues! Thanks so much!
